{
 "title": "Network Traffic",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "LocalIPs",
    "query": "label_values(ntm_bytes_total, src)"
   },
   {
    "name": "Services",
    "query": "label_values(ntm_bytes_total, service)"
   },
   {
    "name": "Protos",
    "query": "label_values(ntm_bytes_total, proto)"
   },
   { "name": "ExcludedServers", "query": "(.*speedtest|1e100\\\\.net).*" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Network Traffic (By Local IP Address)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by(dst) (rate(ntm_bytes_total{dst=~\"$LocalIPs\",src!~\"($ExcludedServers)|($LocalIPs)\",proto=~\"$Protos\",service=~\"$Services\"}[1m]))",
     "legendFormat": "{{ dst }} (Down)"
    },
    {
     "expr": "sum by(src) (rate(ntm_bytes_total{src=~\"$LocalIPs\",dst!~\"($ExcludedServers)|($LocalIPs)\",proto=~\"$Protos\",service=~\"$Services\"}[1m]))",
     "legendFormat": "{{ src }} (Up)"
    }
   ]
  },
  {
   "title": "Downloads (by Local IP)",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by(dst) (increase(ntm_bytes_total{dst=~\"$LocalIPs\",server!~\"($ExcludedServers)|($LocalIPs)\",proto=~\"$Protos\",service=~\"$Services\"}[$__range])) > 0",
     "legendFormat": "{{ dst }}"
    }
   ]
  },
  {
   "title": "Uploads (by Local IP)",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by(src) (increase(ntm_bytes_total{src=~\"$LocalIPs\",client!~\"($ExcludedServers)|($LocalIPs)\",proto=~\"$Protos\",service=~\"$Services\"}[$__range])) > 0",
     "legendFormat": "{{ src }}"
    }
   ]
  },
  {
   "title": "Downloads (by Server)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "topk(10, sum by(src) (increase(ntm_bytes_total{dst=~\"$LocalIPs\",src!~\"($ExcludedServers)|($LocalIPs)\",proto=~\"$Protos\",service=~\"$Services\"}[$__range])))",
     "legendFormat": "{{ src }}"
    }
   ]
  },
  {
   "title": "Uploads (by Server)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "topk(10, sum by(dst) (increase(ntm_bytes_total{src=~\"$LocalIPs\",server!~\"($ExcludedServers)|($LocalIPs)\",proto=~\"$Protos\",service=~\"$Services\"}[$__range])))",
     "legendFormat": "{{ dst }}"
    }
   ]
  },
  {
   "title": "$LocalIPs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "repeat": "LocalIPs",
   "collapsed": true,
   "panels": [
    {
     "title": "Throughput",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum by(dst) (rate(ntm_bytes_total{dst=~\"$LocalIPs\",src!~\"($ExcludedServers)|($LocalIPs)\",proto=~\"$Protos\",service=~\"$Services\"}[1m]))",
       "legendFormat": "{{ server }} (Down)"
      },
      {
       "expr": "sum by(src) (rate(ntm_bytes_total{src=~\"$LocalIPs\",dst!~\"($ExcludedServers)|($LocalIPs)\",proto=~\"$Protos\",service=~\"$Services\"}[1m]))",
       "legendFormat": "{{ client }} (Up)"
      }
     ]
    }
   ]
  }
 ]
}